tap "homebrew/core"
tap "shopify/shopify"
brew "awscli"
brew "curl", args: ["with-openssl"]
brew "git"
brew "gnu-sed"
brew "gnu-units"
brew "grep"
brew "python"
brew "nvm"
brew "p7zip"
brew "rbenv"
brew "rpm"
brew "ruby"
brew "subversion"
brew "the_silver_searcher"
brew "trash"
brew "vim", args: ["with-client-server"]
brew "wget"
brew "xz"
brew "yarn"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "shopify/shopify/toxiproxy"
