tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "rafaelgarrido/caveats"
brew "awscli"
brew "colordiff"
brew "coreutils"
brew "curl"
brew "f3"
brew "fdupes"
brew "fzf"
brew "git"
brew "git-delete-merged-branches"
brew "gnu-sed"
brew "gnu-units"
brew "gnupg"
brew "grep"
brew "httrack"
brew "iperf3"
brew "jq"
brew "make"
brew "mas"
brew "nmap"
brew "node"
brew "nvm"
brew "p7zip"
brew "pandoc"
brew "parquet-cli"
brew "pinentry-mac"
brew "pyenv"
brew "python@3.11"
brew "qrencode"
brew "rbenv"
brew "ruby"
brew "starship"
brew "syncthing", restart_service: true
brew "the_silver_searcher"
brew "trash"
brew "vim"
brew "watch"
brew "wget"
brew "xz"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "rafaelgarrido/caveats/brew-caveats"
cask "1password"
cask "1password-cli"
cask "bettertouchtool"
cask "drawio"
cask "firefox"
cask "font-fira-code"
cask "insomnia"
cask "iterm2-beta"
cask "logi-options-plus"
cask "logseq"
cask "meld"
cask "mysides"
cask "obsidian"
cask "qlmarkdown"
cask "spotify"
cask "visual-studio-code"
brew "rafaelgarrido/caveats/brew-caveats"
mas "Amphetamine", id: 937984704
mas "GoodNotes", id: 1444383602
mas "iA Writer", id: 775737590
mas "Notability", id: 360593530
mas "Pixelmator", id: 407963104
mas "Todoist", id: 585829637
